const features = ["Great", "Excellent", "Tasty", "Fresh", "Strong", "Mild"];
const originCountry = [
  "Ireland",
  "Finland",
  "Usa",
  "Mexico",
  "Sweden",
  "Norway",
  "Denmark",
  "Netherland",
  "Germany",
];
const goesWellWith = [
  "Cheese",
  "Soup",
  "Juice",
  "Yokaline",
  "Soap",
  "Beer",
  "Veal",
  "Tendrils",
  "Wine",
  "Wine ",
  "Pear",
  "Pastry",
  "Onions",
  "Yoghurt",
  "Flour Dark Rye",
  "Crab",
  "Pork Loin Cutlets",
  "Wine",
  "Pate",
  "Pepper",
  "Pork",
  "Straws",
  "Pineapple",
  "Food Colouring",
  "Carbonated Water",
  "Spice",
  "Juice",
  "Wine",
  "Wine",
  "Cocoa Butter",
  "Ostrich - Prime Cut",
];

export { features, originCountry, goesWellWith };
