const productData = [
  {
    id: 0,
    name: "Strong water from Sweden",
    price: "9.5",
    image: 3,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Pork Loin Cutlets",
      detail2: "Pepper",
      detail3: "Veal",
      detail4: "Spice",
    },
  },
  {
    id: 1,
    name: "Mild water from Sweden",
    price: "2.75",
    image: 2,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Spice",
      detail2: "Pork",
      detail3: "Pork",
    },
  },
  {
    id: 2,
    name: "Fresh water from Germany",
    price: "12.65",
    image: 7,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Yoghurt",
      detail2: "Spice",
    },
  },
  {
    id: 3,
    name: "Excellent water from Netherland",
    price: "2.5",
    image: 7,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Cocoa Butter",
      detail2: "Wine",
      detail3: "Crab",
    },
  },
  {
    id: 4,
    name: "Great water from Sweden",
    price: "6.55",
    image: 7,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Pepper",
      detail2: "Spice",
      detail3: "Yoghurt",
      detail4: "Onions",
    },
  },
  {
    id: 5,
    name: "Fresh water from Sweden",
    price: "5.5",
    image: 12,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Veal",
    },
  },
  {
    id: 6,
    name: "Tasty water from Usa",
    price: "15.90",
    image: 12,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Food Colouring",
      detail2: "Flour Dark Rye",
      detail3: "Cheese",
      detail4: "Pear",
    },
  },
  {
    id: 7,
    name: "Excellent water from Norway",
    price: "11.5",
    image: 12,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Pork Loin Cutlets",
      detail2: "Pork Loin Cutlets",
    },
  },
  {
    id: 8,
    name: "Fresh water from Mexico",
    price: "4.85",
    image: 10,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Pork Loin Cutlets",
      detail2: "Cocoa Butter",
      detail3: "Pepper",
      detail4: "Onions",
    },
  },
  {
    id: 9,
    name: "Mild water from Denmark",
    price: "8.35",
    image: 6,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Pork Loin Cutlets",
      detail2: "Juice",
      detail3: "Flour Dark Rye",
      detail4: "Ostrich - Prime Cut",
    },
  },
  {
    id: 10,
    name: "Fresh water from Usa",
    price: "6.75",
    image: 2,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Food Colouring",
      detail2: "Pork Loin Cutlets",
      detail3: "Yoghurt",
    },
  },
  {
    id: 11,
    name: "Fresh water from Germany",
    price: "9.85",
    image: 11,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Pate",
      detail2: "Straws",
    },
  },
  {
    id: 12,
    name: "Excellent water from Mexico",
    price: "6.90",
    image: 4,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Pork Loin Cutlets",
      detail2: "Food Colouring",
      detail3: "Soup",
    },
  },
  {
    id: 13,
    name: "Tasty water from Denmark",
    price: "7.40",
    image: 8,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Flour Dark Rye",
      detail2: "Tendrils",
      detail3: "Beer",
      detail4: "Food Colouring",
    },
  },
  {
    id: 14,
    name: "Excellent water from Usa",
    price: "9.80",
    image: 4,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Tendrils",
      detail2: "Carbonated Water",
      detail3: "Pear",
    },
  },
  {
    id: 15,
    name: "Mild water from Denmark",
    price: "17.30",
    image: 2,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Tendrils",
      detail2: "Onions",
      detail3: "Flour Dark Rye",
      detail4: "Wine",
    },
  },
  {
    id: 16,
    name: "Fresh water from Denmark",
    price: "17.35",
    image: 11,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Wine ",
      detail2: "Pork Loin Cutlets",
      detail3: "Pepper",
      detail4: "Wine ",
    },
  },
  {
    id: 17,
    name: "Mild water from Germany",
    price: "9.80",
    image: 8,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Food Colouring",
    },
  },
  {
    id: 18,
    name: "Mild water from Ireland",
    price: "15.25",
    image: 8,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Carbonated Water",
      detail2: "Beer",
      detail3: "Pineapple",
      detail4: "Soup",
    },
  },
  {
    id: 19,
    name: "Great water from Usa",
    price: "20.10",
    image: 4,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Wine ",
    },
  },
  {
    id: 20,
    name: "Strong water from Netherland",
    price: "9.20",
    image: 1,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Yokaline",
      detail2: "Carbonated Water",
      detail3: "Crab",
      detail4: "Straws",
    },
  },
  {
    id: 21,
    name: "Tasty water from Germany",
    price: "15.40",
    image: 12,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Veal",
      detail2: "Pate",
      detail3: "Wine",
      detail4: "Wine",
    },
  },
  {
    id: 22,
    name: "Strong water from Ireland",
    price: "2.30",
    image: 11,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Yokaline",
      detail2: "Pate",
      detail3: "Pear",
      detail4: "Wine",
    },
  },
  {
    id: 23,
    name: "Excellent water from Mexico",
    price: "10.90",
    image: 1,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Juice",
      detail2: "Food Colouring",
      detail3: "Carbonated Water",
    },
  },
  {
    id: 24,
    name: "Great water from Usa",
    price: "13.35",
    image: 4,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Cheese",
      detail2: "Pork",
      detail3: "Onions",
      detail4: "Pear",
    },
  },
  {
    id: 25,
    name: "Excellent water from Ireland",
    price: "13.80",
    image: 3,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Wine ",
      detail2: "Pear",
      detail3: "Soap",
    },
  },
  {
    id: 26,
    name: "Mild water from Finland",
    price: "1.90",
    image: 11,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Juice",
      detail2: "Veal",
    },
  },
  {
    id: 27,
    name: "Tasty water from Ireland",
    price: "17.30",
    image: 11,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Soap",
      detail2: "Cocoa Butter",
      detail3: "Straws",
      detail4: "Wine ",
    },
  },
  {
    id: 28,
    name: "Mild water from Ireland",
    price: "18.25",
    image: 7,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Crab",
    },
  },
  {
    id: 29,
    name: "Excellent water from Mexico",
    price: "19.85",
    image: 9,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Veal",
      detail2: "Flour Dark Rye",
      detail3: "Food Colouring",
    },
  },
  {
    id: 30,
    name: "Great water from Germany",
    price: "10.85",
    image: 6,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Soup",
      detail2: "Juice",
      detail3: "Onions",
      detail4: "Pate",
    },
  },
  {
    id: 31,
    name: "Fresh water from Netherland",
    price: "3.65",
    image: 6,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Pork",
      detail2: "Juice",
    },
  },
  {
    id: 32,
    name: "Mild water from Ireland",
    price: "17.35",
    image: 6,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Pork",
      detail2: "Ostrich - Prime Cut",
      detail3: "Pate",
      detail4: "Juice",
    },
  },
  {
    id: 33,
    name: "Tasty water from Mexico",
    price: "19.10",
    image: 8,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Spice",
      detail2: "Pate",
      detail3: "Cocoa Butter",
      detail4: "Pork",
    },
  },
  {
    id: 34,
    name: "Strong water from Denmark",
    price: "8.70",
    image: 7,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Pork",
      detail2: "Food Colouring",
      detail3: "Juice",
      detail4: "Soap",
    },
  },
  {
    id: 35,
    name: "Mild water from Norway",
    price: "7.55",
    image: 5,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Wine",
      detail2: "Pork",
      detail3: "Crab",
      detail4: "Pear",
    },
  },
  {
    id: 36,
    name: "Mild water from Netherland",
    price: "18.25",
    image: 8,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Straws",
      detail2: "Flour Dark Rye",
    },
  },
  {
    id: 37,
    name: "Excellent water from Finland",
    price: "19.60",
    image: 1,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Cheese",
      detail2: "Cocoa Butter",
      detail3: "Veal",
    },
  },
  {
    id: 38,
    name: "Excellent water from Netherland",
    price: "15.10",
    image: 1,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Juice",
    },
  },
  {
    id: 39,
    name: "Mild water from Mexico",
    price: "9.10",
    image: 1,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Beer",
      detail2: "Wine",
      detail3: "Wine ",
      detail4: "Onions",
    },
  },
  {
    id: 40,
    name: "Excellent water from Finland",
    price: "8.20",
    image: 7,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Spice",
      detail2: "Soup",
      detail3: "Yokaline",
      detail4: "Pastry",
    },
  },
  {
    id: 41,
    name: "Tasty water from Usa",
    price: "19.35",
    image: 9,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Wine",
      detail2: "Juice",
      detail3: "Juice",
      detail4: "Beer",
    },
  },
  {
    id: 42,
    name: "Mild water from Netherland",
    price: "1.10",
    image: 4,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Food Colouring",
      detail2: "Crab",
      detail3: "Pork",
    },
  },
  {
    id: 43,
    name: "Fresh water from Netherland",
    price: "17.50",
    image: 2,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Flour Dark Rye",
      detail2: "Pork Loin Cutlets",
      detail3: "Straws",
      detail4: "Wine",
    },
  },
  {
    id: 44,
    name: "Great water from Denmark",
    price: "18.90",
    image: 1,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Tendrils",
      detail2: "Wine",
      detail3: "Spice",
    },
  },
  {
    id: 45,
    name: "Great water from Netherland",
    price: "4.35",
    image: 4,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Ostrich - Prime Cut",
      detail2: "Pork Loin Cutlets",
      detail3: "Spice",
      detail4: "Straws",
    },
  },
  {
    id: 46,
    name: "Great water from Netherland",
    price: "11.25",
    image: 5,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Pate",
      detail2: "Cocoa Butter",
      detail3: "Pork",
      detail4: "Juice",
    },
  },
  {
    id: 47,
    name: "Strong water from Sweden",
    price: "20.95",
    image: 9,
    rating: 5,
    quantity: 1,
    productDetails: {
      detail1: "Wine ",
      detail2: "Pear",
      detail3: "Juice",
      detail4: "Cocoa Butter",
    },
  },
  {
    id: 48,
    name: "Strong water from Denmark",
    price: "14.5",
    image: 6,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Veal",
      detail2: "Tendrils",
      detail3: "Wine",
    },
  },
  {
    id: 49,
    name: "Fresh water from Mexico",
    price: "1.45",
    image: 3,
    rating: 3,
    quantity: 1,
    productDetails: {
      detail1: "Soap",
      detail2: "Juice",
      detail3: "Food Colouring",
      detail4: "Wine",
    },
  },
  {
    id: 50,
    name: "Fresh water from Finland",
    price: "12.60",
    image: 8,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Spice",
      detail2: "Pineapple",
      detail3: "Ostrich - Prime Cut",
      detail4: "Cocoa Butter",
    },
  },
  {
    id: 51,
    name: "Tasty water from Norway",
    price: "4.60",
    image: 2,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Cheese",
      detail2: "Straws",
      detail3: "Wine",
      detail4: "Juice",
    },
  },
  {
    id: 52,
    name: "Tasty water from Norway",
    price: "15.65",
    image: 12,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Tendrils",
      detail2: "Wine ",
      detail3: "Wine ",
      detail4: "Carbonated Water",
    },
  },
  {
    id: 53,
    name: "Excellent water from Germany",
    price: "4.55",
    image: 5,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Yokaline",
      detail2: "Pineapple",
      detail3: "Veal",
      detail4: "Juice",
    },
  },
  {
    id: 54,
    name: "Excellent water from Denmark",
    price: "1.20",
    image: 8,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Crab",
      detail2: "Juice",
      detail3: "Juice",
      detail4: "Spice",
    },
  },
  {
    id: 55,
    name: "Great water from Finland",
    price: "5.65",
    image: 2,
    rating: 2,
    quantity: 1,
    productDetails: {
      detail1: "Pork",
      detail2: "Juice",
      detail3: "Flour Dark Rye",
      detail4: "Juice",
    },
  },
  {
    id: 56,
    name: "Fresh water from Finland",
    price: "8.5",
    image: 9,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Wine",
      detail2: "Pastry",
      detail3: "Pate",
      detail4: "Beer",
    },
  },
  {
    id: 57,
    name: "Fresh water from Usa",
    price: "14.25",
    image: 3,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Juice",
      detail2: "Wine",
      detail3: "Wine",
      detail4: "Wine",
    },
  },
  {
    id: 58,
    name: "Fresh water from Denmark",
    price: "15.70",
    image: 10,
    rating: 1,
    quantity: 1,
    productDetails: {
      detail1: "Ostrich - Prime Cut",
      detail2: "Soap",
      detail3: "Pineapple",
      detail4: "Cheese",
    },
  },
  {
    id: 59,
    name: "Mild water from Sweden",
    price: "11.20",
    image: 8,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Tendrils",
      detail2: "Juice",
      detail3: "Spice",
      detail4: "Wine",
    },
  },
  {
    id: 60,
    name: "Mild water from Sweden",
    price: "11.20",
    image: 8,
    rating: 4,
    quantity: 1,
    productDetails: {
      detail1: "Tendrils",
      detail2: "Juice",
      detail3: "Spice",
      detail4: "Wine",
    },
  },
];

export { productData };
